server:
  port: 8001

mybatis:
  type-aliases-package: com.feng.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://49.234.28.149:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456


#eureka:
#  client:
#    service-url:
##      defaultZone: http://ImOK:123456@49.234.28.149:9000/eureka/  # eureka注册中心服务地址
#      defaultZone: http://ImOK:123456@localhost:9000/eureka/  # eureka注册中心服务地址
#  instance:
#    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
#    preferIpAddress: true # 鼠标移动到服务名上时，跳转连接是否显示IP


car:
  type: madeInChina

person:
  sex: 男

xxl:
  job:
    accessToken:
    executor:
      appname: xxl-job-app
      ip:
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: -1
      port: 9988
    admin:
      addresses: http://127.0.0.1:8061/xxl-job-admin
