server:
  port: 9090

spring:
  application:
    name: consumer
#  security: # eureka管理后台安全认证
#    user:
#      name: ImOK #用户名
#      password: 123456 #密码
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.234.28.149:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    xa:
      properties:
        useInformationSchema : true # 可以获取tables注释信息

  redis:
    host: 49.234.28.149
    password: gefeng
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://ImOK:123456@49.234.28.149:9000/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    preferIpAddress: true # 鼠标移动到服务名上时，跳转连接是否显示IP

xxl:
  job:
    accessToken:
    executor:
      appname: demo
      ip:
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: -1
      port: 9999
    admin:
      addresses: http://localhost:8086/xxl-job-admin




