server:
  port: 9090

spring:
  application:
    name: consumer
  security: # eureka管理后台安全认证
    user:
      name: ImOK #用户名
      password: 123456 #密码

eureka:
  client:
    service-url:
      defaultZone: http://ImOK:123456@configserver-1.com:9000/eureka/,http://configserver-2.com:9006/eureka/,http://configserver-3.com:9008/eureka/