server:
  port: 9696

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  # 开启sql日志打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

